# Site settings
title: Alerta que salpica
email: muralyluces@gmail.com
url: https://eduardofebres.github.io
description: "Paredes pintadas de américa latina"
keywords: "street-art, muralismo, América Latina, arte urbano, grafiti, mural"
skills: "Paredes pintadas de América Latina"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e1042d #80B3FF
  primary-rgb: "225,4,45" #"128,179,255"
  secondary: 201f1f #FD6E8A
  secondary-dark: 282828 #A2122F

# Footer settings
footer:
  copyright: Freelancer
  location:
  social: Síguenos
  credits: Crédito

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/alertaqsalpica
  - title: facebook
    url: http://facebook.com/alertaqsalpicalibro
  - title: instagram
    url: http://instagram.com/alertaquesalpica

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Credits content
credits: 'AqS fue concebido por la cooperativa Ej&eacutercito Comunicacional de Liberaci&oacuten (Venezuela), Andr&eacutes Sap&iacuten (Ecuador), el Colectivo Dexpierte (Colombia) y Marialina Maviz&uacute (Costa Rica). Fue desarrollado por el E.C.L. y publicado por la editorial Ocho Libros (Chile).'

# Build settings
markdown: kramdown
permalink: pretty
